### ISSUE TITLE
Support new info block design style

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill.tech#245]
- [Updated info block design style with icon](https://www.figma.com/file/BiBWpUOUQb7FoKxZV4G7gB/%F0%9F%93%96----Documentation?node-id=150%3A729)
- And a new `details` variant: similar to [`details` variant](https://vitepress.vuejs.org/guide/markdown#default-title) from vitepress, we have designed [our new `details` variant](https://www.figma.com/file/BiBWpUOUQb7FoKxZV4G7gB/%F0%9F%93%96----Documentation?node-id=211%3A1362).

![image](https://user-images.githubusercontent.com/66248476/185503419-ec9156d1-8270-4d4a-bd5d-1fbf48478059.png)

![image](https://user-images.githubusercontent.com/66248476/185503625-7bb96ac3-e442-48b4-9f54-ec6b6063244e.png)

**Comment by EiffelFly** [comment]
It turns out we don't need to have another custom-block variant, we can just use <details>
