### ISSUE TITLE
Add link to text block

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill.tech#338]
Link `READ GETTING STARTED GUIDE` with https://instill.tech/docs

![image](https://user-images.githubusercontent.com/66248476/201786999-cd3d1aa8-339e-4ba7-bdea-f60e04fbc60b.png)

**Comment by EiffelFly** [comment]
IMO, this text block is not designed for link usage, especially other text blocks that don't have links, making this one hard to notice. I have two suggestions here:

- Re-write the wording and not link to the documentation page, that we had already linked to four different destinations of our documentation, and I think it's efficient
- If we want to put another CTA here to link to the documentation. Right here (please ignore the ugly design)

![截圖 2022-11-16 下午3 52 42](https://user-images.githubusercontent.com/57251712/202120129-e2faf5c6-6f73-4e4f-adce-e1be6b68cce1.png)

**Comment by xiaofei-du** [comment]
let's change it to `Open to integrations`

**Comment by EiffelFly** [comment]
This commit had been fixed with #346
