### ISSUE TITLE
Make the section title text space smaller

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill.tech#339]
e.g.,

![image](https://user-images.githubusercontent.com/66248476/201789733-a7872791-11c0-47d5-ad74-dbee74912024.png)

![image](https://user-images.githubusercontent.com/66248476/201789758-9a62305b-99c7-4622-86f3-0eb620a70ea7.png)

**Comment by iamnamananand996** [comment]
Hi @EiffelFly ,

I had made the following changes in `css` in `tailwind.config.js` file.

**Previous**
```
".word-spacing-tight": {
     wordSpacing: "-0.25rem",
 },
 ".word-spacing-tighter": {
     wordSpacing: "-0.5rem",
},
".word-spacing-super-tight": {
    wordSpacing: "-1.0rem",
},
```

**Cuurent**
```
".word-spacing-tight": {
     wordSpacing: "-0.4rem",
 },
 ".word-spacing-tighter": {
     wordSpacing: "-0.8rem",
},
".word-spacing-super-tight": {
    wordSpacing: "-1.2rem",
},
```

hope, this will fix the spacing problem.

**Comment by EiffelFly** [comment]
@iamnamananand996 Thanks for your reminder, I think this issue had already been solved but without closing it
