### ISSUE TITLE
Upgrade to Nextjs 13

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/instill.tech#374]
Nextjs has lots of useful feature that we can use such as layout and image optimization. We need to upgrade to 13 asap.

**Comment by EiffelFly** [comment]
This had already finished

**Comment by alceil** [comment]
Can I work on this? @EiffelFly

**Comment by EiffelFly** [comment]
@alceil For sure, we are happy that you would like to toggle this issue!! If you have any question you can find me on our discord server or leave the related message in this issue.

**Comment by alceil** [comment]
Got it thanks @EiffelFly

**Comment by EiffelFly** [comment]
close with #515
