### ISSUE TITLE
Aovid getting rate-limited by GitHub API

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill.tech#454]
The GitHub API rate-limit error slows down local development.

![image](https://user-images.githubusercontent.com/66248476/214191743-b646e7e5-991a-43be-92b0-123806be0026.png)

**Comment by EiffelFly** [comment]
@xiaofei-du you can setup your github personal access token in `.env.local` please follow the contribution guideline, I had updated this part https://github.com/instill-ai/instill.tech/blob/main/CONTRIBUTING.md#general-guideline-for-setting-up-project
