### ISSUE TITLE
Allow Null value for metadata `aiTask`, `sourceConnector` and `destinationConnector` fields

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill.tech#455]
Some tutorials can't be labelled with a specific tag for the following metadata fields
```
aiTask: "objectDetection"
sourceConnector: "HTTP"
destinationConnector: "HTTP"
```

We can make these metadata fields accept the `Null` value, also needs to refactor the UI to reflect this change.

**Comment by EiffelFly** [comment]
Confirmed the UI changes, close with the #459 PR.
