### ISSUE TITLE
GitHub and Discord are not shown in documentation navigation

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/instill.tech#492]
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/66248476/221385322-b76acc9e-75c3-4f0e-afa8-6717cf5652e2.png">

https://github.com/instill-ai/instill.tech/blob/28665a306136fbb597a3cdf579143ef52e27cdc8/content.config.tsx#L185-L214

**Comment by EiffelFly** [comment]
close with #497
