### ISSUE TITLE
feature-request: dedicated toggle block component

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/instill.tech#531]
## Context

**Please raise your implementation overview here before implementing**

Right now we are using the regular markdown toggle syntax and then cover custom style on it to implement toggle block. Here is the implementation

```md
<details>
  <summary></summary>
</details>
```

https://github.com/instill-ai/instill.tech/blob/00830b1be8c2655c01b1c39de509e8a0b502e667/src/styles/docs.css#L158

But this becomes not flexible. We want to build a dedicated toggle block (with component name `ToggleBlock`) with MDX and refactor all the toggle block in docs to adapt this new MDX component. 

You could reference how we build InfoBlock

https://github.com/instill-ai/instill.tech/blob/00830b1be8c2655c01b1c39de509e8a0b502e667/src/components/ui/MdxInfoBlock.tsx#L9

- The toggle interaction may use some react state.
- You don't need to worry about how mdx deal with children. Just treat it like InfoBlock did and mdx will handle the rest.
- The design will align with current design
  
<details>
  <summary>Current Design</summary>

  ![截圖 2023-03-23 下午5 07 38](https://user-images.githubusercontent.com/57251712/227155187-26392f82-186d-4f16-ac62-caf3f3f7c058.png)

 
![截圖 2023-03-23 下午5 07 45](https://user-images.githubusercontent.com/57251712/227155169-dff21352-efe3-4436-b0da-e48bc573569d.png)
</details>

**Comment by iamnamananand996** [comment]
Hi @EiffelFly , the current implementation will look like this

```
  import { ReactElement } from "react";
  
  export type MdxToggleBlockProps = {
    children: ReactElement;
  };
  
  export const MdxToggleBlock = ({ children }: MdxToggleBlockProps) => {
    return children;
  };
```

please let me know, if we want to add more features into it.

**Comment by iamnamananand996** [comment]
@EiffelFly , is the above implementation looks good, shall I create a pull request for the above.

**Comment by EiffelFly** [comment]
@iamnamananand996 Correct me if I am wrong. I imagine your implementation will be

```
<InfoBlock className="instill-scoped-info-block">
  <details>
      <summary>**Why do you build VDP?**</summary>
        Modern data stack misses unstructured data processing.
    </details>
</InfoBlock>
```

Then we can do something with CSS to apply custom style?

```css
article > .instill-scoped-info-block > details {
  padding: 20px 25px;
  background-color: #FAFAFA;
  margin-top: 20px;
  margin-bottom: 20px;
  border-radius: 5px;
  border-left: 5px solid #5c5c5c;
}
```

**Comment by iamnamananand996** [comment]
@EiffelFly, you are correct, I have added params to add styles also now.

**Comment by EiffelFly** [comment]
close with #532
